name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    # Skip building pull requests from the same repository
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != '${{ github.repository }}'
    runs-on: windows-2022
    strategy:
      matrix:
        os: [windows-2022]
    env:
      BUILD_TYPE: Release
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v5

    - name: Install Static Qt
      run: |
        Invoke-WebRequest https://github.com/microcai/static-build-qt6/releases/download/qt6_673_static_64/qt6_673_static_64.zip -OutFile .\qt6_673_static_64.zip
        expand-archive -path "qt6_673_static_64.zip"

    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Build
      run: |
        cmake -G Ninja -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} "-DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install" -DCMAKE_PREFIX_PATH="${{ github.workspace }}/qt6_673_static_64/Qt6_binaries" -B build
        cmake --build build

    - name: Upload generic artifacts
      uses: actions/upload-artifact@v4.4.0
      with:
        name: upkg
        path: build/bin/release

    - name: zip the result
      run: |
        cd build/bin/release
        7z a upkg.zip upkg.exe

    - name: upload Release
      uses: softprops/action-gh-release@master
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/bin/release/upkg.zip
